# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-25 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyApp', '0004_auto_20171024_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='status',
            field=models.CharField(choices=[('h', 'Hide'), ('o', 'Open')], default='h', max_length=1),
            preserve_default=False,
        ),
    ]
