# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-21 12:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studyApp', '0005_study_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='study',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='comment',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studyApp.Study'),
        ),
    ]
