# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-21 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyApp', '0006_auto_20171121_1218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='study',
            name='tag_set',
            field=models.ManyToManyField(to='studyApp.Tag'),
        ),
    ]
