# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-23 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyApp', '0007_auto_20171121_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='tag_set',
            field=models.ManyToManyField(blank=True, to='studyApp.Tag'),
        ),
    ]
