# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-23 09:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studyApp', '0009_auto_20171123_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_user_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
