# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-10 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyApp', '0010_auto_20171123_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='end_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='location',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='study',
            name='start_date',
            field=models.DateField(blank=True),
        ),
    ]
